### PR TITLE
misc refactors

### PR DESCRIPTION
**Pull request by cjbassi**

### CODE REVIEW

**Comment by ArturKovacs** [comment]
The only change that's objectively an improvement in my opinion is renaming `linux.rs` to `xdg.rs`. The other changes seem to be a matter of personal preference.

**Comment by cjbassi** [comment]
Well `extern crate` is legacy, is it not? And the tests folder is documented here: https://doc.rust-lang.org/book/ch11-03-test-organization.html. I don't think it's standard practice to have a tests file in the src dir.

**Comment by cjbassi** [comment]
Just to clarify, I was only doing these small changes and PRs as I was getting familiar with the project. I plan on doing more substantive changes going forward. I didn't mean to throw a bunch of seemingly unimportant PRs your way.

**Comment by ArturKovacs** [comment]
> Well extern crate is legacy, is it not?

Fair enough. That can be removed too.

> And the tests folder is documented here [...] I don't think it's standard practice to have a tests file in the src dir.

Oookay. All things considered moving the tests into `integration_test.rs` is an improvement.

However I still believe that renaming the tests you suggested is a matter of personal preference and as such I wouldn't be comfortable merging those.

**Comment by cjbassi** [comment]
The tests rename was done to match common convention too. Example: https://doc.rust-lang.org/stable/rust-by-example/testing/unit_testing.html

**Comment by ArturKovacs** [comment]
I should have replied to this one. I didn't mean to abandon this conversation like that. For the record: the reason why it's a good idea to prepend "test_" to the name of test functions is that the test function's names would collide with the tested function's name when importing all function names form the tested module (e.g. `super::*`).

I adopted some of these changes on the master branch but if you are intersted, I'd be open to merge the rest of the changes once the merge conflicts are resolved.

**Comment by ArturKovacs** [comment]
Closing this as the module "linux" does not exist anymore, as it's been replaced with the freedesktop module, and I'm happy with the naming there.

**Pull request closed without merging**
